import { Metadata } from 'next';
import localFont from 'next/font/local';
import Provider from '@/src/lib/Provider';
import './globals.css';

const pretendardVariable = localFont({
  src: '../src/lib/style/fonts/PretendardVariable.woff2',
  weight: '100 900',
  display: 'swap',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendardVariable.variable}`}>
        <Provider>
          <div className="flex min-h-screen flex-col">{children}</div>
        </Provider>
      </body>
    </html>
  );
}
