import { Metadata } from 'next';
import localFont from 'next/font/local';
import Provider from '@/src/lib/Provider';
import './globals.css';
import Modal from '@/src/shared/components/modal/Modal';

const pretendardVariable = localFont({
  src: '../src/lib/style/fonts/PretendardVariable.woff2',
  weight: '100 900',
  display: 'swap',
  variable: '--font-pretendard',
});

const digitalNumbers = localFont({
  src: '../src/lib/style/fonts/DigitalNumbers-Regular.ttf',
  weight: '400',
  display: 'swap',
  variable: '--font-digital-numbers',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider>
      <html lang="ko">
        <body className={`${pretendardVariable.variable} ${digitalNumbers.variable}`}>
          <div className="flex min-h-screen flex-col">{children}</div>
          <Modal />
        </body>
      </html>
    </Provider>
  );
}
